@echo off
echo Starting PHP FastCGI...
RunHiddenConsole D:/server/AppServ/php5/php-cgi.exe -b 127.0.0.1:9000 -c D:/server/AppServ/php5/php.ini
echo Starting nginx...
start "" D:/server/AppServ/nginx/nginx.exe
echo MySQL service starting...
net start mysql
Exit